### ISSUE TITLE
Catserver 1.12.2 打开GUI后报错

### ISSUE THREAD

**Issue by XiaoShuaiOwO** [Roinflam/GardenBank#1]
`[Craft Scheduler Thread - 7022/WARN]: [GardenBank] Plugin GardenBank v1.0.0 generated an exception while executing task 1268159
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.LEGACY_SUNFLOWER
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_351]
        at org.bukkit.Material.valueOf(Material.java:73) ~[Material.class:git-CatServer-1.12.2-090a6ffb]
        at pers.tany.yukinoaapi.realizationpart.builder.ItemBuilder.<init>(ItemBuilder.java:154) ~[?:?]
        at pers.tany.gardenbank.gui.BankInterface.update(BankInterface.java:130) ~[?:?]
        at pers.tany.gardenbank.gui.BankInterface.access$000(BankInterface.java:28) ~[?:?]
        at pers.tany.gardenbank.gui.BankInterface$1.run(BankInterface.java:103) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-090a6ffb]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_351]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_351]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]
`

**Comment by XiaoShuaiOwO** [comment]
更改为IItemBuilder diamond = new ItemBuilder("DOUBLE_PLANT");后不再报错
